---
- hosts: kubernetes-worker-nodes
  become: true
  vars_files:
  - env_variables
  tasks:
  - name: Copying token to worker nodes
    copy: src={{ token_file }} dest=join_token

 # - name: Joining worker nodes with kubernetes master
#    shell: |
 #    sudo su 
     #kubeadm reset -f
 #    cat join_token | tail -2 > out.sh
 #    sh out.sh
 #    exit
